In [3]:
import pandas as pd

In [4]:
baseball = pd.read_csv("./data/baseball.csv")
baseball.head(10)

,Unnamed: 0,Rk,Year,Tm,Lg,G,W,L,Ties,W.L.,...,R,RA,Attendance,BatAge,PAge,X.Bat,X.P,Top.Player,Managers,current
0,1,1,2016,Arizona Diamondbacks,NL West,162,69,93,0,0.426,...,752,890,"2,036,216",26.7,26.4,50,29,J.Segura (5.7),C.Hale (69-93),Arizona Diamondbacks
1,2,2,2015,Arizona Diamondbacks,NL West,162,79,83,0,0.488,...,720,713,"2,080,145",26.6,27.1,50,27,P.Goldschmidt (8.8),C.Hale (79-83),Arizona Diamondbacks
2,3,3,2014,Arizona Diamondbacks,NL West,162,64,98,0,0.395,...,615,742,"2,073,730",27.6,28.0,52,25,P.Goldschmidt (4.5),K.Gibson (63-96) and A.Trammell (1-2),Arizona Diamondbacks
3,4,4,2013,Arizona Diamondbacks,NL West,162,81,81,0,0.500,...,685,695,"2,134,895",28.1,27.6,44,23,P.Goldschmidt (7.1),K.Gibson (81-81),Arizona Diamondbacks
4,5,5,2012,Arizona Diamondbacks,NL West,162,81,81,0,0.500,...,734,688,"2,177,617",28.3,27.4,48,23,A.Hill (5.0),K.Gibson (81-81),Arizona Diamondbacks
5,6,6,2011,Arizona Diamondbacks,NL West,162,94,68,0,0.580,...,731,662,"2,105,432",28.2,27.4,51,25,J.Upton (6.1),K.Gibson (94-68),Arizona Diamondbacks
6,7,7,2010,Arizona Diamondbacks,NL West,162,65,97,0,0.401,...,713,836,"2,056,697",26.8,27.9,48,28,C.Young (5.4),A.Hinch (31-48) and K.Gibson (34-49),Arizona Diamondbacks
7,8,8,2009,Arizona Diamondbacks,NL West,162,70,92,0,0.432,...,720,782,"2,128,765",26.5,27.7,45,24,D.Haren (7.1),B.Melvin (12-17) and A.Hinch (58-75),Arizona Diamondbacks
8,9,9,2008,Arizona Diamondbacks,NL West,162,82,80,0,0.506,...,720,706,"2,509,924",26.7,29.4,41,20,D.Haren (6.6),B.Melvin (82-80),Arizona Diamondbacks
9,10,10,2007,Arizona Diamondbacks,NL West,162,90,72,0,0.556,...,712,732,"2,325,249",26.6,28.2,47,26,B.Webb (5.9),B.Melvin (90-72),Arizona Diamondbacks

In [5]:
baseball.sort_values('Tm', ascending=False,na_position='first').head()

,Unnamed: 0,Rk,Year,Tm,Lg,G,W,L,Ties,W.L.,...,R,RA,Attendance,BatAge,PAge,X.Bat,X.P,Top.Player,Managers,current
1491,1492,88,1929,Washington Senators,AL,153,71,81,1,0.467,...,730,776,"355,506",28.2,27.5,34,14,F.Marberry (6.7),W.Johnson (71-81),Minnesota Twins
1486,1487,83,1934,Washington Senators,AL,155,66,86,3,0.434,...,729,806,"330,074",29.8,31.2,39,17,H.Manush (4.7),J.Cronin (66-86),Minnesota Twins
1469,1470,66,1951,Washington Senators,AL,154,62,92,0,0.403,...,672,764,"695,167",28.7,31.3,38,17,E.Yost (4.0),B.Harris (62-92),Minnesota Twins
1468,1469,65,1952,Washington Senators,AL,157,78,76,3,0.506,...,598,608,"699,457",28.5,31.8,43,18,B.Porterfield (5.3),B.Harris (78-76),Minnesota Twins
1467,1468,64,1953,Washington Senators,AL,152,76,76,0,0.500,...,687,614,"595,594",28.6,30.9,39,15,M.Vernon (5.4),B.Harris (76-76),Minnesota Twins

In [6]:
baseball.sort_values(['Tm', 'Lg'], ascending=False,na_position='first').head()

,Unnamed: 0,Rk,Year,Tm,Lg,G,W,L,Ties,W.L.,...,R,RA,Attendance,BatAge,PAge,X.Bat,X.P,Top.Player,Managers,current
2495,2496,46,1971,Washington Senators,AL East,159,63,96,0,0.396,...,537,660,"655,156",27.6,26.4,39,14,B.Gogolewski (2.9),T.Williams (63-96),Texas Rangers
2496,2497,47,1970,Washington Senators,AL East,162,70,92,0,0.432,...,626,689,"824,789",28.1,27.6,40,17,A.Rodriguez (5.6),T.Williams (70-92),Texas Rangers
2497,2498,48,1969,Washington Senators,AL East,162,86,76,0,0.531,...,694,644,"918,106",27.8,27.0,36,16,K.McMullen (5.9),T.Williams (86-76),Texas Rangers
1460,1461,57,1960,Washington Senators,AL,154,73,81,0,0.474,...,672,696,"743,404",27.3,26.8,37,18,P.Ramos (4.1),C.Lavagetto (73-81),Minnesota Twins
1461,1462,58,1959,Washington Senators,AL,154,63,91,0,0.409,...,619,701,"615,372",27.0,26.9,40,16,C.Pascual (8.6),C.Lavagetto (63-91),Minnesota Twins

In [9]:
baseball.sort_values(['Tm', 'Lg'], ascending=[False,True],na_position='first').head()

,Unnamed: 0,Rk,Year,Tm,Lg,G,W,L,Ties,W.L.,...,R,RA,Attendance,BatAge,PAge,X.Bat,X.P,Top.Player,Managers,current
1460,1461,57,1960,Washington Senators,AL,154,73,81,0,0.474,...,672,696,"743,404",27.3,26.8,37,18,P.Ramos (4.1),C.Lavagetto (73-81),Minnesota Twins
1461,1462,58,1959,Washington Senators,AL,154,63,91,0,0.409,...,619,701,"615,372",27.0,26.9,40,16,C.Pascual (8.6),C.Lavagetto (63-91),Minnesota Twins
1462,1463,59,1958,Washington Senators,AL,156,61,93,2,0.396,...,553,747,"475,288",28.1,26.3,39,17,D.Hyde (4.6),C.Lavagetto (61-93),Minnesota Twins
1463,1464,60,1957,Washington Senators,AL,154,55,99,0,0.357,...,603,808,"457,079",28.4,25.5,41,19,R.Sievers (4.6),C.Dressen (4-16) and C.Lavagetto (51-83),Minnesota Twins
1464,1465,61,1956,Washington Senators,AL,155,59,95,1,0.383,...,652,924,"431,647",26.8,24.8,33,14,C.Stobbs (4.6),C.Dressen (59-95),Minnesota Twins

In [11]:
baseball.sort_index(ascending=False,inplace=True)
baseball.head()

,Unnamed: 0,Rk,Year,Tm,Lg,G,W,L,Ties,W.L.,...,R,RA,Attendance,BatAge,PAge,X.Bat,X.P,Top.Player,Managers,current
2593,2594,48,1969,Montreal Expos,NL East,162,52,110,0,0.321,...,582,791,"1,212,608",27.6,26.8,42,18,R.Staub (6.2),G.Mauch (52-110),Washington Nationals
2592,2593,47,1970,Montreal Expos,NL East,162,73,89,0,0.451,...,687,807,"1,424,683",27.7,26.7,40,17,R.Staub (6.3),G.Mauch (73-89),Washington Nationals
2591,2592,46,1971,Montreal Expos,NL East,162,71,90,1,0.441,...,622,729,"1,290,963",28.3,27.0,33,12,R.Staub (5.9),G.Mauch (71-90),Washington Nationals
2590,2591,45,1972,Montreal Expos,NL East,156,70,86,0,0.449,...,513,609,"1,142,145",26.9,25.9,30,12,M.Marshall (4.0),G.Mauch (70-86),Washington Nationals
2589,2590,44,1973,Montreal Expos,NL East,162,79,83,0,0.488,...,668,702,"1,246,863",27.7,26.2,41,15,K.Singleton (5.7),G.Mauch (79-83),Washington Nationals